Change for adaption of equations of spatial neuron except morphology
brian-team/brian2tools pull request #51
Opened 2024-08-22 11:11 UTC by sparsh-989

Below is the added functionallity
https://gist.github.com/sparsh989/41b4168241a6d8b319a51138b80e8602

2024-08-22 13:14 UTC, sparsh-989 commented
<img width="1657" alt="Screenshot 2024-08-22 at 6 42 54 PM" src="https://github.com/user-attachments/assets/8df8e917-6f1b-4042-a80b-b8b31b4f809c">
for the below test file
from brian2 import *
import brian2tools.mdexport
# set device 'markdown'
set_device('markdown', filename='model1_description')
defaultclock.dt = 0.01*ms

# Morphology
diameter = 1*um
length = 300*um
Cm = 1*uF/cm**2
Ri = 150*ohm*cm
N = 200
morpho = Cylinder(diameter=diameter, length=length, n=N)

# Passive channels
gL = 1e-4*siemens/cm**2
EL = -70*mV
eqs = '''
Im = gL * (EL - v) : amp/meter**2
I : amp (point current)
'''

neuron = SpatialNeuron(morphology=morpho, model=eqs, Cm=Cm, Ri=Ri,
                       method='exponential_euler')
neuron.v = EL
la = Ri * Cm**(0.5)  

print("Electrotonic length: %s" % la)

neuron.I[0] = 0.02*nA # injecting at the left end
run(100*ms, report='text')

2024-08-22 19:45 UTC, mstimberg requested changes

2024-08-22 19:45 UTC, mstimberg commented on brian2tools/baseexport/collector.py
> +    Collect information from `brian2.groups.neurongroup.NeuronGroup`
Please refer to `SpatialNeuron` here

2024-08-22 19:45 UTC, mstimberg commented on brian2tools/baseexport/collector.py
> +    group : brian2.groups.neurongroup.NeuronGroup
`SpatialNeuron` here and below as well

2024-08-22 19:45 UTC, mstimberg commented on brian2tools/baseexport/collector.py
> +    print("hello2")
Please remove

2024-08-22 19:46 UTC, mstimberg requested changes
I did not test things in detail, but from a basic check this all looks good! I left a few minor comments

2024-08-23 21:56 UTC, mstimberg approved these changes

2024-08-23 21:57 UTC, merged